# Generated by Django 5.1.1 on 2024-10-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='descripcion',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='eventos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/image'),
        ),
        migrations.AddField(
            model_name='city',
            name='poblacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='visitar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
