# Generated by Django 5.1.1 on 2024-10-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_city_descripcion_city_eventos_city_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='estilo_css',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
