# Generated by Django 5.1.1 on 2024-10-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_city_estilo_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='descripcion',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='visitar',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
