# Generated by Django 5.1.1 on 2024-10-30 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_city_descripcion_alter_city_visitar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar_Turistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(null=True, upload_to='static/image')),
                ('img2', models.ImageField(null=True, upload_to='static/image')),
                ('img3', models.ImageField(null=True, upload_to='static/image')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='routes.city')),
            ],
        ),
    ]
