# Generated by Django 5.1.1 on 2024-10-31 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_lugar_turistico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='descripcion',
            new_name='contacto',
        ),
        migrations.RemoveField(
            model_name='city',
            name='poblacion',
        ),
    ]
