# Generated by Django 5.1.1 on 2024-10-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_rename_descripcion_city_contacto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='contacto',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='city',
            name='visitar',
        ),
        migrations.AddField(
            model_name='city',
            name='poblacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lugar_turistico',
            name='visitar',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
