# Generated by Django 5.1.1 on 2024-10-31 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_rename_visitar_lugar_turistico_visitar1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='eventos',
        ),
    ]
