# Generated by Django 5.1.1 on 2024-11-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_remove_city_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar_turistico',
            name='title1',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lugar_turistico',
            name='title2',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lugar_turistico',
            name='title3',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
