# Generated by Django 5.1.1 on 2024-11-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_lugar_turistico_title1_lugar_turistico_title2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='estilo_css',
        ),
    ]
